import { describe, expect, it } from 'bun:test';
import { animatedSpriteSheet } from './animated-sprite-sheet';

describe('animatedSpriteSheet', () => {
  it('should parse a sprite sheet with animations into a dict with rect[]', () => {
    const tileSize = 16;
    expect(
      animatedSpriteSheet({
        frameWidth: tileSize,
        frameHeight: tileSize * 2,
        width: 512,
        height: 512,
        animations: [
          {
            name: 'idle',
            row: 6,
            frames: 4,
            startFrame: 8,
          },
          {
            name: 'run',
            row: 6,
            frames: 4,
            startFrame: 12,
          },
          {
            name: 'hit',
            row: 6,
            frames: 1,
            startFrame: 16,
          },
          {
            name: 'full row test',
            row: 7,
          },
          {
            name: 'full row test with start frame',
            row: 8,
            startFrame: 5,
          },
          {
            name: 'row test with frame limit',
            row: 9,
            frames: 6,
          },
        ],
      }),
    ).toEqual({
      idle: [
        {
          x: 128,
          y: 192,
          width: 16,
          height: 32,
        },
        {
          x: 144,
          y: 192,
          width: 16,
          height: 32,
        },
        {
          x: 160,
          y: 192,
          width: 16,
          height: 32,
        },
        {
          x: 176,
          y: 192,
          width: 16,
          height: 32,
        },
      ],
      run: [
        {
          x: 192,
          y: 192,
          width: 16,
          height: 32,
        },
        {
          x: 208,
          y: 192,
          width: 16,
          height: 32,
        },
        {
          x: 224,
          y: 192,
          width: 16,
          height: 32,
        },
        {
          x: 240,
          y: 192,
          width: 16,
          height: 32,
        },
      ],
      hit: [
        {
          x: 256,
          y: 192,
          width: 16,
          height: 32,
        },
      ],
      'full row test': [
        {
          x: 0,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 16,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 32,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 48,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 64,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 80,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 96,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 112,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 128,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 144,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 160,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 176,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 192,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 208,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 224,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 240,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 256,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 272,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 288,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 304,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 320,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 336,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 352,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 368,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 384,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 400,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 416,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 432,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 448,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 464,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 480,
          y: 224,
          width: 16,
          height: 32,
        },
        {
          x: 496,
          y: 224,
          width: 16,
          height: 32,
        },
      ],
      'full row test with start frame': [
        {
          x: 80,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 96,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 112,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 128,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 144,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 160,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 176,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 192,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 208,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 224,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 240,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 256,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 272,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 288,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 304,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 320,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 336,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 352,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 368,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 384,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 400,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 416,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 432,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 448,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 464,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 480,
          y: 256,
          width: 16,
          height: 32,
        },
        {
          x: 496,
          y: 256,
          width: 16,
          height: 32,
        },
      ],
      'row test with frame limit': [
        {
          x: 0,
          y: 288,
          width: 16,
          height: 32,
        },
        {
          x: 16,
          y: 288,
          width: 16,
          height: 32,
        },
        {
          x: 32,
          y: 288,
          width: 16,
          height: 32,
        },
        {
          x: 48,
          y: 288,
          width: 16,
          height: 32,
        },
        {
          x: 64,
          y: 288,
          width: 16,
          height: 32,
        },
        {
          x: 80,
          y: 288,
          width: 16,
          height: 32,
        },
      ],
    });
  });
});
