name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
permissions:
  contents: read
jobs:
  test:
    name: Format, Lint, Typecheck, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # run scripts
      - run: bun install # renovate does not update the lockfile properly, so --frozen-lockfile would break dependency updates
      - run: bun run build # will run check, which must run before lint
      - run: bun lint
      - run: bun format
      - run: bun test