name: Publish
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  test:
    name: Format, Lint, Typecheck, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      # run scripts
      - run: bun install
      - run: bun run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLISH_VERSION: ${{ github.ref_name }}