name: Release
on:
  push:
    tags: ['*']
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: |
          RELEASE_NOTES=$(bunx pixel-craft-tooling extract-release-notes "$GITHUB_REF_NAME")
          echo 'RELEASE_NOTES<<EOF' >> "$GITHUB_ENV"
          echo "$RELEASE_NOTES" >> "$GITHUB_ENV"
          echo 'EOF' >> "$GITHUB_ENV"

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ env.RELEASE_NOTES }}

  publish:
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      # run scripts
      - run: bun install --frozen-lockfile
      - run: bun release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLISH_VERSION: ${{ github.ref_name }}